name: FTP Deployment

on:
  push:
    branches:
      - main  # Trigger the action when pushing to the main branch
  pull_request:
    branches:
      - main  # Trigger the action when a PR is merged into the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Check out the code from the repository

      - name: Set up FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21  # Default FTP port
          local-dir: ./  # The local directory to deploy
          server-dir: /transfunnel/  # The remote directory to deploy to
          
      - name: Deploy to FTP
        run: |
          echo "Deployment started1"
